services:
  nvim:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOTFILES_GIT_URL: https://github.com/wizalexander/dotfiles.git
    platform: linux/amd64
    image: wiz-nvim:0.11.5
    container_name: nvim
    stdin_open: true
    tty: true
    user: 1000:1000
    working_dir: /home/dev
    volumes:
      - dev-home:/home/dev
      - ~/:/home/dev/hostfiles
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: nvim
volumes:
  dev-home:
